[toolchain]
package_manager = "npm"
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
web3_academy = "FdJCM2mmwrLXXu6ZDbsogBpBABUb7JxH8x91ZDXELqDc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
